INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('AB', 'Algona Brownies', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('AB2', 'Indianapolis ABCs', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('ABC', 'Indianapolis ABCs', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('AC1', 'All Cubans', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('AC2', 'All Cubans', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('ACG', 'Akron Grays / Cleveland Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('ALT', 'Altoona Mountain City', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('ANA', 'Los Angeles Angels of Anaheim', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('ARI', 'Arizona Diamondbacks', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('ATH', 'Philadelphia Athletics', 'N', 'PNA');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('ATL', 'Atlanta Braves', 'Y', 'BNA');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BAL', 'Baltimore Orioles', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BBB', 'Birmingham Black Barons', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BBS', 'Baltimore Black Sox', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BCA', 'Atlanta Black Crackers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BEG', 'Baltimore Elite Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BFB', 'Buffalo Bisons', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BFL', 'Buffalo Bisons', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BG1', 'Atlantic City Bacharach Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BG2', 'Atlantic City Bacharach Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BLC', 'Baltimore Canaries', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BLO', 'Baltimore Orioles', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BLT', 'Baltimore Terrapins', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BLU', 'Baltimore Monumentals', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BNA', 'Boston Red Stockings', 'NA', 'ATL');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BOS', 'Boston Red Sox', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BR2', 'Brooklyn Royal Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BRA', 'Brooklyn Atlantics', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BRD', 'Boston Reds', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BRG', 'Brooklyn Gladiators', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BRS', 'Boston Reds', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BTT', 'Brooklyn Tip-Tops', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BUF', 'Buffalo Bisons', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('BWW', 'Brooklyn Ward''s Wonders', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CAG', 'Chicago American Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CBB', 'Columbus Blue Birds', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CBE', 'Cleveland Buckeyes', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CBG', 'Cuban Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CBK', 'Columbus Buckeyes', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CBL', 'Cleveland Blues', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CBN', 'Cleveland Browns', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CCG', 'Chicago Columbia Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CEL', 'Cleveland Elites', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CEN', 'Philadelphia Centennials', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CFC', 'Cleveland Forest Citys', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CHC', 'Chicago Cubs', 'Y', 'CNA');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CHH', 'Chicago Whales', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CHP', 'Chicago Pirates', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CHT', 'Cleveland Hornets', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CHW', 'Chicago White Sox', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CIN', 'Cincinnati Reds', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CIU', 'Chicago Unions', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CKK', 'Cincinnati Kelly''s Killers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CL2', 'Cleveland Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CLE', 'Cleveland Indians', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CLI', 'Cleveland Infants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CLS', 'Columbus Solons', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CLV', 'Cleveland Spiders', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CNA', 'Chicago White Stockings', 'NA', 'CHC');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CNR', 'Cincinnati Reds', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('COB', 'Columbus Buckeyes', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('COG', 'Chicago Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('COL', 'Colorado Rockies', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('COR', 'Cincinnati Outlaw Reds', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('COT', 'Columbus Turf Club', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CPI', 'Chicago/Pittsburgh (Union League)', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CRS', 'Cleveland Red Sox', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CSE', 'Cuban Stars East', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CSW', 'Cuban Stars West', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CT', 'Cincinnati Tigers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CTG', 'Cleveland Tigers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CTS', 'Cleveland Tate Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CUP', 'Pollock''s Cuban Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('CXG', 'Cuban X Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('DET', 'Detroit Tigers', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('DS', 'Detroit Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('DTN', 'Detroit Wolverines', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('DTS', 'Detroit Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('DW', 'Detroit Wolves', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('DYM', 'Dayton Marcos', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('ECK', 'Brooklyn Eckfords', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('FLA', 'Florida Marlins', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('FLP', 'French Lick Plutos', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('GOR', 'New York Gorhams', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('HAR', 'Hartford Dark Blues', 'N', 'HNA');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('HBG', 'Harrisburg Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('HG', 'Homestead Grays', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('HIL', 'Hilldale Club', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('HNA', 'Hartford Dark Blues', 'NA', 'HAR');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('HOU', 'Houston Astros', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('IA', 'Indianapolis Athletics', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('IBL', 'Indianapolis Blues', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('IC', 'Cincinnati-Indianapolis Clowns', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('IHO', 'Indianapolis Hoosiers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('IND', 'Indianapolis Hoosiers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('JRC', 'Jacksonville Red Caps', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('KCC', 'Kansas City Cowboys', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('KCG', 'Kansas City Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('KCM', 'Kansas City Monarchs', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('KCN', 'Kansas City Cowboys', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('KCP', 'Kansas City Packers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('KCR', 'Kansas City Royals', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('KCU', 'Kansas City Cowboys', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('KEK', 'Fort Wayne Kekiongas', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('KRG', 'Kansas City Royal Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('LAD', 'Los Angeles Dodgers', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('LEL', 'Chicago Leland Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('LGR', 'Louisville Grays', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('LOU', 'Louisville Colonels', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('LRG', 'Little Rock Grays', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('LVB', 'Louisville Black Caps', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MAN', 'Middletown Mansfields', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MAR', 'Baltimore Marylands', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MB', 'Milwaukee Bears', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MGS', 'Montgomery Grey Sox', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MIL', 'Milwaukee Brewers', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MIN', 'Minnesota Twins', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MLA', 'Milwaukee Brewers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MLG', 'Milwaukee Grays', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MLU', 'Milwaukee Brewers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MOH', 'Schenectady Mohawk Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MRM', 'Monroe Monarchs', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('MRS', 'Memphis Red Sox', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NAT', 'Washington Nationals', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NBY', 'New York Black Yankees', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('ND', 'Newark Dodgers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NE', 'Newark Eagles', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NEW', 'Newark Pepper', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NHV', 'New Haven Elm Citys', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NLG', 'New York Lincoln Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NLS', 'New York Lincoln Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NNA', 'New York Mutuals', 'NA', 'NYU');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NS', 'Newark Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NWB', 'Newark Browns', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NYC', 'New York Cubans', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NYI', 'New York Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NYM', 'New York Mets', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NYP', 'New York Metropolitans', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NYU', 'New York Mutuals', 'N', 'NNA');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('NYY', 'New York Yankees', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('OAK', 'Oakland Athletics', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('OKM', 'Oklahoma Monarchs', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('OLY', 'Washington Olympics', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PBB', 'Pittsburgh Burghers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PBG', 'Philadelphia Bacharach Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PBK', 'Pittsburgh Keystones', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PBS', 'Pittsburgh Rebels', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PC', 'Pittsburgh Crawfords', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PG', 'Philadelphia Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PHA', 'Philadelphia Athletics', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PHI', 'Philadelphia Phillies', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PHK', 'Philadelphia Keystones', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PHQ', 'Philadelphia Athletics', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PIT', 'Pittsburgh Pirates', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PNA', 'Philadelphia Athletics', 'NA', 'ATH');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PRO', 'Providence Grays', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PS', 'Philadelphia Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PTG', 'Philadelphia Tigers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('PWS', 'Philadelphia White Stockings', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('QG', 'Philadelphia Quaker Giants', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('RES', 'Elizabeth Resolutes', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('RIC', 'Richmond Virginians', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('ROC', 'Rochester Broncos', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('ROK', 'Rockford Forest Citys', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SBS', 'St. Louis Brown Stockings', 'N', 'SNA');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SC1', 'Stars of Cuba', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SDP', 'San Diego Padres', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SEA', 'Seattle Mariners', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SEN', 'Washington Black Senators', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SFG', 'San Francisco Giants', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SL2', 'St. Louis Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SLI', 'St. Louis Terriers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SLM', 'St. Louis Maroons', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SLR', 'St. Louis Red Stockings', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SLS', 'St. Louis Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SNA', 'St. Louis Brown Stockings', 'NA', 'SBS');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SNH', 'St. Louis-New Orleans Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SPG', 'St. Paul Gophers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('STL', 'St. Louis Cardinals', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('STP', 'St. Paul Apostles', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SYR', 'Syracuse Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('SYS', 'Syracuse Stars', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('TBD', 'Tampa Bay Rays', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('TEX', 'Texas Rangers', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('TLM', 'Toledo Maumees', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('TOL', 'Toledo Blue Stockings', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('TOR', 'Toronto Blue Jays', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('TRO', 'Troy Haymakers', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('TRT', 'Troy Trojans', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('TT', 'Toledo Tigers', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WAP', 'Washington Pilots', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WAS', 'Washington Senators', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WBL', 'Washington Blue Legs', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WBS', 'West Baden Sprudels', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WES', 'Keokuk Westerns', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WIL', 'Wilmington Quicksteps', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WNA', 'Washington Nationals', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WNL', 'Washington Nationals', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WNT', 'Washington Nationals', 'NA', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WOR', 'Worcester Ruby Legs', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WP', 'Washington Potomacs', 'N', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WSN', 'Washington Nationals', 'Y', '');
INSERT INTO "TeamsFranchises" ("franchID", "franchName", "active", "NAassoc") VALUES ('WST', 'Washington Statesmen', 'N', '');
