-- Generated from lahman.db (People)
CREATE TABLE "People" (
    "ID" integer NOT NULL,
    "playerID" varchar(20) NOT NULL,
    "birthYear" integer,
    "birthMonth" integer,
    "birthDay" integer,
    "birthCity" varchar(100),
    "birthCountry" varchar(50),
    "birthState" varchar(50),
    "deathYear" integer,
    "deathMonth" integer,
    "deathDay" integer,
    "deathCountry" varchar(50),
    "deathState" varchar(50),
    "deathCity" varchar(100),
    "nameFirst" varchar(100),
    "nameLast" varchar(100),
    "nameGiven" varchar(100),
    "weight" varchar(10),
    "height" varchar(10),
    "bats" varchar(10),
    "throws" varchar(10),
    "debut" varchar(20),
    "bbrefID" varchar(20),
    "finalGame" varchar(20),
    "retroID" varchar(20),
    CONSTRAINT "People_pkey" PRIMARY KEY ("playerID")
);
