-- Generated from lahman.db (PitchingPost)
CREATE TABLE "PitchingPost" (
    "playerID" varchar(20) NOT NULL,
    "yearID" smallint NOT NULL,
    "round" varchar(10) NOT NULL,
    "teamID" varchar(4),
    "lgID" varchar(3),
    "W" smallint,
    "L" smallint,
    "G" smallint,
    "GS" smallint,
    "CG" smallint,
    "SHO" smallint,
    "SV" smallint,
    "IPouts" integer,
    "H" smallint,
    "ER" smallint,
    "HR" smallint,
    "BB" smallint,
    "SO" smallint,
    "BAOpp" double precision,
    "ERA" double precision,
    "IBB" smallint,
    "WP" smallint,
    "HBP" smallint,
    "BK" smallint,
    "BFP" smallint,
    "GF" smallint,
    "R" smallint,
    "SH" smallint,
    "SF" smallint,
    "GIDP" smallint,
    CONSTRAINT "PitchingPost_pkey" PRIMARY KEY ("playerID", "yearID", "round"),
    CONSTRAINT "PitchingPost_teamID_lgID_yearID_fkey" FOREIGN KEY ("teamID", "lgID", "yearID") REFERENCES "Teams" ("teamID", "lgID", "yearID"),
    CONSTRAINT "PitchingPost_playerID_fkey" FOREIGN KEY ("playerID") REFERENCES "People" ("playerID")
);
