-- Generated from lahman.db (Pitching)
CREATE TABLE "Pitching" (
    "playerID" varchar(20) NOT NULL,
    "yearID" smallint NOT NULL,
    "stint" smallint NOT NULL,
    "teamID" varchar(4),
    "lgID" varchar(3),
    "W" smallint,
    "L" smallint,
    "G" smallint,
    "GS" smallint,
    "CG" smallint,
    "SHO" smallint,
    "SV" smallint,
    "IPouts" smallint,
    "H" smallint,
    "ER" smallint,
    "HR" smallint,
    "BB" smallint,
    "SO" smallint,
    "BAOpp" double precision,
    "ERA" double precision,
    "IBB" smallint,
    "WP" smallint,
    "HBP" smallint,
    "BK" smallint,
    "BFP" smallint,
    "GF" smallint,
    "R" smallint,
    "SH" smallint,
    "SF" smallint,
    "GIDP" smallint,
    CONSTRAINT "Pitching_pkey" PRIMARY KEY ("playerID", "yearID", "stint"),
    CONSTRAINT "Pitching_teamID_lgID_yearID_fkey" FOREIGN KEY ("teamID", "lgID", "yearID") REFERENCES "Teams" ("teamID", "lgID", "yearID"),
    CONSTRAINT "Pitching_playerID_fkey" FOREIGN KEY ("playerID") REFERENCES "People" ("playerID")
);
