-- Generated from lahman.db (Teams)
CREATE TABLE "Teams" (
    "yearID" smallint NOT NULL,
    "lgID" varchar(3) NOT NULL,
    "teamID" varchar(4) NOT NULL,
    "franchID" varchar(4),
    "divID" varchar(2),
    "Rank" smallint,
    "G" smallint,
    "Ghome" smallint,
    "W" smallint,
    "L" smallint,
    "DivWin" varchar(1),
    "WCWin" varchar(1),
    "LgWin" varchar(1),
    "WSWin" varchar(1),
    "R" smallint,
    "AB" smallint,
    "H" smallint,
    "2B" smallint,
    "3B" smallint,
    "HR" smallint,
    "BB" smallint,
    "SO" smallint,
    "SB" smallint,
    "CS" smallint,
    "HBP" smallint,
    "SF" smallint,
    "RA" smallint,
    "ER" smallint,
    "ERA" double precision,
    "CG" smallint,
    "SHO" smallint,
    "SV" smallint,
    "IPouts" smallint,
    "HA" smallint,
    "HRA" smallint,
    "BBA" smallint,
    "SOA" smallint,
    "E" smallint,
    "DP" smallint,
    "FP" double precision,
    "name" varchar(100),
    "park" varchar(255),
    "attendance" integer,
    "BPF" smallint,
    "PPF" smallint,
    "teamIDBR" varchar(4),
    "teamIDlahman45" varchar(4),
    "teamIDretro" varchar(4),
    CONSTRAINT "Teams_pkey" PRIMARY KEY ("teamID", "lgID", "yearID"),
    CONSTRAINT "Teams_franchID_fkey" FOREIGN KEY ("franchID") REFERENCES "TeamsFranchises" ("franchID")
);
