<Project Sdk="Aspire.AppHost.Sdk/13.2.3">

  <ItemGroup>
    <ProjectReference Include="..\baseball-history-web\baseball-history-web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>59fbd8c3-4111-4410-868e-6d860473e7d5</UserSecretsId>
  </PropertyGroup>

</Project>
